### ISSUE TITLE
Sort objects in array 

### ISSUE THREAD

**Issue by saraswatkarthik** [saraswatkarthik/Data-comparison#1]
https://github.com/saraswatkarthik/Data-comparison/blob/45d2125749cac3b12e4e5bcb2cbe4370ea8af74d/script.js#L97

Sort this array of objects depending on value of "overall" property for example object with highest numeric value will sit on 0th key.

**Comment by Shivamyana19** [comment]
hii saraswatkarthik , i want to work on this . It will be my first contribution, so help me whenever needed. Please assign it to me.

**Comment by saraswatkarthik** [comment]
> hii saraswatkarthik , i want to work on this . It will be my first contribution, so help me whenever needed. Please assign it to me.

👍👍👍

**Comment by saraswatkarthik** [comment]
> > hii saraswatkarthik , i want to work on this . It will be my first contribution, so help me whenever needed. Please assign it to me.
> 
> 👍👍👍

This is solved thanks for your attention.
